# SPDX-License-Identifier: CC-BY-NC-ND-4.0
#
# base.frag - CHC5 Buildroot base configuration
#
# Copyright (c) 2026 Circuit Valley - Author: Gaurav Singh
# https://creativecommons.org/licenses/by-nc-nd/4.0/

BR2_arm=y
BR2_cortex_a9=y
BR2_ARM_ENABLE_NEON=y
BR2_ARM_ENABLE_VFP=y

BR2_KERNEL_HEADERS_6_6=y

BR2_INIT_SYSTEMD=y

BR2_PACKAGE_TZDATA=y
BR2_TARGET_TZ_INFO=y
BR2_TARGET_TZ_ZONELIST="etcetera"
BR2_TARGET_LOCALTIME="Etc/UTC"

BR2_TARGET_ROOTFS_TAR=y
BR2_TARGET_ROOTFS_TAR_GZIP=y
BR2_TARGET_ROOTFS_SQUASHFS=y
BR2_TARGET_ROOTFS_SQUASHFS4_XZ=y

BR2_PACKAGE_CHC5_PLATFORMD=y
BR2_PACKAGE_CHC5_WEBD=y
BR2_PACKAGE_CAMCFGD=y
BR2_PACKAGE_GVCP_SERVER=y

BR2_PACKAGE_XZ=y

BR2_PACKAGE_LIBGPIOD=y

BR2_PACKAGE_CIVETWEB=y
BR2_PACKAGE_CIVETWEB_LIB=y

BR2_PACKAGE_OVERRIDE_FILE="$(BR2_EXTERNAL_CHC5_PATH)/local.mk"

BR2_PACKAGE_SYSTEMD=y

BR2_PACKAGE_SYSTEMD_PSTORE=y
BR2_PACKAGE_SYSTEMD_NETWORKD=y
BR2_PACKAGE_SYSTEMD_TIMESYNCD=y
BR2_PACKAGE_SYSTEMD_COREDUMP=y
BR2_PACKAGE_SYSTEMD_RANDOMSEED=y

BR2_PACKAGE_RAUC=y
BR2_PACKAGE_OPENSSL=y
BR2_PACKAGE_LIBCURL=y
BR2_PACKAGE_UBOOT_TOOLS=y
BR2_PACKAGE_UBOOT_TOOLS_FWPRINTENV=y

BR2_PACKAGE_DOSFSTOOLS=y
BR2_PACKAGE_E2FSPROGS=y

BR2_PACKAGE_HOST_GENIMAGE=y
BR2_PACKAGE_HOST_DOSFSTOOLS=y
BR2_PACKAGE_HOST_MTOOLS=y
BR2_PACKAGE_HOST_E2FSPROGS=y

BR2_PACKAGE_IPUTILS=y
BR2_PACKAGE_IPUTILS_ARPING=y
BR2_PACKAGE_IPROUTE2=y

BR2_PACKAGE_LINUXPTP=y

BR2_ROOTFS_POST_BUILD_SCRIPT="$(BR2_EXTERNAL_CHC5_PATH)/board/chc5/post-build.sh"
