/* SPDX-License-Identifier: CC-BY-NC-ND-4.0 */
/*
 * chc5-v4l2-controls.h - CHC5 V4L2 control IDs
 *
 * Copyright (c) 2026 Circuit Valley - Author: Gaurav Singh
 * https://creativecommons.org/licenses/by-nc-nd/4.0/
 */

#ifndef _UAPI_LINUX_CHC5_V4L2_CONTROLS_H
#define _UAPI_LINUX_CHC5_V4L2_CONTROLS_H

#include <linux/v4l2-controls.h>

#define V4L2_CID_USER_CHC5_BASE		(V4L2_CID_USER_BASE + 0x1000)

#define CHC5_XVSUB_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x000)
#define CHC5CCM_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x100)
#define CHC5WBG_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x200)
#define CHC5AES_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x300)
#define CHC5CAMIO_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x400)
#define CHC5GAMMA_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x500)
#define CHC5DMSC_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x600)
#define CHC5PWLE_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x700)
#define CHC5PWLC_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x800)
#define CHC5EMB_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x900)
#define CHC5GW_CID_BASE			(V4L2_CID_USER_CHC5_BASE + 0xA00)
#define CHC5RC_CID_BASE			(V4L2_CID_USER_CHC5_BASE + 0xB00)
#define CHC5_VDMA_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0xD00)
#define CHC5SHARPEN_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0xE00)
#define CHC5TPG_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0xF00)
#define CHC5CSI2RX_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x1000)
#define CHC5CROP_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x1100)
#define CHC5SENSOR_CID_BASE		(V4L2_CID_USER_CHC5_BASE + 0x1200)

#define CHC5_XVSUB_CID_FRAME_NUM	(CHC5_XVSUB_CID_BASE + 0)
#define CHC5_XVSUB_CID_FRAME_DEN	(CHC5_XVSUB_CID_BASE + 1)

#define CHC5CCM_CID_MATRIX		(CHC5CCM_CID_BASE + 0)
#define CHC5CCM_CID_CLAMP_MIN		(CHC5CCM_CID_BASE + 1)
#define CHC5CCM_CID_CLIP_MAX		(CHC5CCM_CID_BASE + 2)
#define CHC5CCM_CID_ENABLE		(CHC5CCM_CID_BASE + 3)

#define CHC5WBG_CID_GAINS		(CHC5WBG_CID_BASE + 0)
#define CHC5WBG_CID_PHASE_MAP		(CHC5WBG_CID_BASE + 1)
#define CHC5WBG_CID_ENABLE		(CHC5WBG_CID_BASE + 2)

#define CHC5AES_CID_SUBSAMPLE		(CHC5AES_CID_BASE + 0)
#define CHC5AES_CID_AWB_ENABLE		(CHC5AES_CID_BASE + 1)
#define CHC5AES_CID_GRAY_ENABLE		(CHC5AES_CID_BASE + 2)
#define CHC5AES_CID_GRAY_THR		(CHC5AES_CID_BASE + 3)
#define CHC5AES_CID_Y_LO		(CHC5AES_CID_BASE + 4)
#define CHC5AES_CID_Y_HI		(CHC5AES_CID_BASE + 5)
#define CHC5AES_CID_GATE_GAIN_R		(CHC5AES_CID_BASE + 6)
#define CHC5AES_CID_GATE_GAIN_B		(CHC5AES_CID_BASE + 7)

#define CHC5CAMIO_CID_ENABLE		(CHC5CAMIO_CID_BASE + 0)
#define CHC5CAMIO_CID_SOFT_RESET	(CHC5CAMIO_CID_BASE + 1)
#define CHC5CAMIO_CID_IN_FUNCTION	(CHC5CAMIO_CID_BASE + 2)
#define CHC5CAMIO_CID_IN_ACTIVATION	(CHC5CAMIO_CID_BASE + 3)
#define CHC5CAMIO_CID_IN_INVERT		(CHC5CAMIO_CID_BASE + 4)
#define CHC5CAMIO_CID_IN_DELAY		(CHC5CAMIO_CID_BASE + 5)
#define CHC5CAMIO_CID_IN_DIVIDER	(CHC5CAMIO_CID_BASE + 6)
#define CHC5CAMIO_CID_STROBE_ENABLE	(CHC5CAMIO_CID_BASE + 7)
#define CHC5CAMIO_CID_STROBE_INVERT	(CHC5CAMIO_CID_BASE + 8)
#define CHC5CAMIO_CID_STROBE_SRC	(CHC5CAMIO_CID_BASE + 9)
#define CHC5CAMIO_CID_STROBE_DELAY	(CHC5CAMIO_CID_BASE + 12)
#define CHC5CAMIO_CID_STROBE_DURATION	(CHC5CAMIO_CID_BASE + 14)
#define CHC5CAMIO_CID_STROBE_MINON	(CHC5CAMIO_CID_BASE + 15)
#define CHC5CAMIO_CID_OUT_SOURCE	(CHC5CAMIO_CID_BASE + 16)
#define CHC5CAMIO_CID_OUT_INVERT	(CHC5CAMIO_CID_BASE + 17)
#define CHC5CAMIO_CID_OUT_USER_VALUE	(CHC5CAMIO_CID_BASE + 18)
#define CHC5CAMIO_CID_SYNC_ROLE		(CHC5CAMIO_CID_BASE + 19)
#define CHC5CAMIO_CID_SYNC_XVS_POL	(CHC5CAMIO_CID_BASE + 22)
#define CHC5CAMIO_CID_SYNC_XHS_POL	(CHC5CAMIO_CID_BASE + 23)
#define CHC5CAMIO_CID_SYNC_ROLE_BY	(CHC5CAMIO_CID_BASE + 24)
#define CHC5CAMIO_CID_SYNC_TRIG_ROUTE	(CHC5CAMIO_CID_BASE + 26)
#define CHC5CAMIO_CID_STATUS		(CHC5CAMIO_CID_BASE + 27)
#define CHC5CAMIO_CID_IN_STATUS		(CHC5CAMIO_CID_BASE + 28)
#define CHC5CAMIO_CID_SYNC_STATUS	(CHC5CAMIO_CID_BASE + 29)

#define CHC5GAMMA_CID_RED_GAMMA		(CHC5GAMMA_CID_BASE + 0)
#define CHC5GAMMA_CID_GREEN_GAMMA	(CHC5GAMMA_CID_BASE + 1)
#define CHC5GAMMA_CID_BLUE_GAMMA	(CHC5GAMMA_CID_BASE + 2)
#define CHC5GAMMA_CID_ENABLE		(CHC5GAMMA_CID_BASE + 3)
#define CHC5GAMMA_CID_TABLE		(CHC5GAMMA_CID_BASE + 4)

#define CHC5DMSC_CID_ENABLE		(CHC5DMSC_CID_BASE + 0)
#define CHC5DMSC_CID_BYPASS		(CHC5DMSC_CID_BASE + 1)
#define CHC5DMSC_CID_ZIPPER_EN		(CHC5DMSC_CID_BASE + 2)
#define CHC5DMSC_CID_EDGE_THRESH	(CHC5DMSC_CID_BASE + 3)
#define CHC5DMSC_CID_ZIPPER_HITS	(CHC5DMSC_CID_BASE + 4)
#define CHC5DMSC_CID_FRAME_CNT		(CHC5DMSC_CID_BASE + 5)

#define CHC5PWLE_CID_TABLE		(CHC5PWLE_CID_BASE + 0)
#define CHC5PWLE_CID_ENABLE		(CHC5PWLE_CID_BASE + 1)

#define CHC5PWLC_CID_CURVE		(CHC5PWLC_CID_BASE + 0)
#define CHC5PWLC_CID_ENABLE		(CHC5PWLC_CID_BASE + 1)
#define CHC5PWLC_CID_CLIP_CLEAR		(CHC5PWLC_CID_BASE + 2)

#define CHC5EMB_CID_ENABLE		(CHC5EMB_CID_BASE + 0)
#define CHC5EMB_CID_CLR_STICKY		(CHC5EMB_CID_BASE + 1)

#define CHC5GW_CID_RED_GAMMA		(CHC5GW_CID_BASE + 0)
#define CHC5GW_CID_GREEN_GAMMA		(CHC5GW_CID_BASE + 1)
#define CHC5GW_CID_BLUE_GAMMA		(CHC5GW_CID_BASE + 2)
#define CHC5GW_CID_ENABLE		(CHC5GW_CID_BASE + 3)
#define CHC5GW_CID_TABLE		(CHC5GW_CID_BASE + 4)

#define CHC5RC_CID_MODE			(CHC5RC_CID_BASE + 0)
#define CHC5RC_CID_ENABLE		(CHC5RC_CID_BASE + 1)
#define CHC5RC_CID_CLR_STICKY		(CHC5RC_CID_BASE + 2)

#define CHC5_VDMA_CID_ENABLE		(CHC5_VDMA_CID_BASE + 0)

#define CHC5SHARPEN_CID_CORING		(CHC5SHARPEN_CID_BASE + 0)
#define CHC5SHARPEN_CID_OVERSHOOT	(CHC5SHARPEN_CID_BASE + 1)
#define CHC5SHARPEN_CID_BYPASS		(CHC5SHARPEN_CID_BASE + 2)
#define CHC5SHARPEN_CID_ENABLE		(CHC5SHARPEN_CID_BASE + 3)

#define CHC5CSI2RX_CID_FORCE_DT		(CHC5CSI2RX_CID_BASE + 0)
#define CHC5CSI2RX_CID_DROP_UNTIL_FS	(CHC5CSI2RX_CID_BASE + 1)
#define CHC5CSI2RX_CID_FNUM_INTERNAL	(CHC5CSI2RX_CID_BASE + 2)
#define CHC5CSI2RX_CID_LNUM_INTERNAL	(CHC5CSI2RX_CID_BASE + 3)

#define CHC5CROP_CID_ENABLE		(CHC5CROP_CID_BASE + 0)
#define CHC5CROP_CID_BYPASS		(CHC5CROP_CID_BASE + 1)
#define CHC5CROP_CID_DROP_UNTIL_SOF	(CHC5CROP_CID_BASE + 2)
#define CHC5CROP_CID_STATUS		(CHC5CROP_CID_BASE + 3)
#define CHC5CROP_CID_ACTIVE_WINDOW	(CHC5CROP_CID_BASE + 4)

#define CHC5SENSOR_CID_OB_LEFT		(CHC5SENSOR_CID_BASE + 0)
#define CHC5SENSOR_CID_OB_TOP		(CHC5SENSOR_CID_BASE + 1)
#define CHC5SENSOR_CID_OB_RIGHT		(CHC5SENSOR_CID_BASE + 2)
#define CHC5SENSOR_CID_OB_BOTTOM	(CHC5SENSOR_CID_BASE + 3)

#define CHC5SENSOR_CID_OB_ON_IMAGE_DT	(CHC5SENSOR_CID_BASE + 4)

#define CHC5SENSOR_CID_PWL_CURVE	(CHC5SENSOR_CID_BASE + 5)
#define CHC5SENSOR_PWL_CURVE_LEN	133

#endif
