# CHC5.xdc - CHC5 board pin and timing constraints
# Copyright (c) 2026 Circuit Valley - Author: Gaurav Singh
# SPDX-License-Identifier: CC-BY-NC-ND-4.0
# https://creativecommons.org/licenses/by-nc-nd/4.0/

set_property INTERNAL_VREF 0.6 [get_iobanks 35]

set_property CONFIG_VOLTAGE 2.5 [get_iobanks 35]

set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_0_clk_hs_p]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_0_clk_hs_n]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_n[3]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_n[2]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_n[1]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_n[0]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_p[3]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_p[2]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_p[1]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_0_data_lp_p[0]}]
set_property IOSTANDARD HSUL_12 [get_ports mipi_phy_if_0_clk_lp_n]
set_property IOSTANDARD HSUL_12 [get_ports mipi_phy_if_0_clk_lp_p]

set_property PACKAGE_PIN K17 [get_ports mipi_phy_if_0_clk_hs_p]
set_property PACKAGE_PIN K18 [get_ports mipi_phy_if_0_clk_hs_n]
set_property PACKAGE_PIN K16 [get_ports mipi_phy_if_0_clk_lp_p]
set_property PACKAGE_PIN J16 [get_ports mipi_phy_if_0_clk_lp_n]

set_property PACKAGE_PIN L19 [get_ports {mipi_phy_if_0_data_hs_p[0]}]
set_property PACKAGE_PIN L20 [get_ports {mipi_phy_if_0_data_hs_n[0]}]
set_property PACKAGE_PIN N15 [get_ports {mipi_phy_if_0_data_lp_p[0]}]
set_property PACKAGE_PIN M15 [get_ports {mipi_phy_if_0_data_lp_n[0]}]

set_property PACKAGE_PIN K19 [get_ports {mipi_phy_if_0_data_hs_p[1]}]
set_property PACKAGE_PIN J19 [get_ports {mipi_phy_if_0_data_hs_n[1]}]
set_property PACKAGE_PIN M14 [get_ports {mipi_phy_if_0_data_lp_p[1]}]
set_property PACKAGE_PIN L14 [get_ports {mipi_phy_if_0_data_lp_n[1]}]

set_property PACKAGE_PIN M19 [get_ports {mipi_phy_if_0_data_hs_p[2]}]
set_property PACKAGE_PIN M20 [get_ports {mipi_phy_if_0_data_hs_n[2]}]
set_property PACKAGE_PIN M18 [get_ports {mipi_phy_if_0_data_lp_p[2]}]
set_property PACKAGE_PIN N16 [get_ports {mipi_phy_if_0_data_lp_n[2]}]

set_property PACKAGE_PIN L16 [get_ports {mipi_phy_if_0_data_hs_p[3]}]
set_property PACKAGE_PIN L17 [get_ports {mipi_phy_if_0_data_hs_n[3]}]
set_property PACKAGE_PIN L15 [get_ports {mipi_phy_if_0_data_lp_p[3]}]
set_property PACKAGE_PIN M17 [get_ports {mipi_phy_if_0_data_lp_n[3]}]

set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_1_clk_hs_p]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_1_clk_hs_n]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_n[3]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_n[2]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_n[1]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_n[0]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_p[3]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_p[2]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_p[1]}]
set_property IOSTANDARD HSUL_12 [get_ports {mipi_phy_if_1_data_lp_p[0]}]
set_property IOSTANDARD HSUL_12 [get_ports mipi_phy_if_1_clk_lp_n]
set_property IOSTANDARD HSUL_12 [get_ports mipi_phy_if_1_clk_lp_p]

set_property PACKAGE_PIN H16 [get_ports mipi_phy_if_1_clk_hs_p]
set_property PACKAGE_PIN K14 [get_ports mipi_phy_if_1_clk_lp_n]
set_property PACKAGE_PIN J14 [get_ports mipi_phy_if_1_clk_lp_p]
set_property PACKAGE_PIN F19 [get_ports {mipi_phy_if_1_data_hs_p[0]}]
set_property PACKAGE_PIN G17 [get_ports {mipi_phy_if_1_data_hs_p[1]}]
set_property PACKAGE_PIN J18 [get_ports {mipi_phy_if_1_data_hs_p[2]}]
set_property PACKAGE_PIN J20 [get_ports {mipi_phy_if_1_data_hs_p[3]}]
set_property PACKAGE_PIN F17 [get_ports {mipi_phy_if_1_data_lp_n[3]}]
set_property PACKAGE_PIN G20 [get_ports {mipi_phy_if_1_data_lp_n[2]}]
set_property PACKAGE_PIN G15 [get_ports {mipi_phy_if_1_data_lp_n[1]}]
set_property PACKAGE_PIN D18 [get_ports {mipi_phy_if_1_data_lp_n[0]}]
set_property PACKAGE_PIN F16 [get_ports {mipi_phy_if_1_data_lp_p[3]}]
set_property PACKAGE_PIN G19 [get_ports {mipi_phy_if_1_data_lp_p[2]}]
set_property PACKAGE_PIN H15 [get_ports {mipi_phy_if_1_data_lp_p[1]}]
set_property PACKAGE_PIN E17 [get_ports {mipi_phy_if_1_data_lp_p[0]}]

set_property DIFF_TERM false [get_ports mipi_phy_if_0_clk_hs_p]
set_property DIFF_TERM false [get_ports mipi_phy_if_0_clk_hs_n]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_p[3]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_n[3]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_p[2]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_n[2]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_p[1]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_n[1]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_p[0]}]
set_property DIFF_TERM false [get_ports {mipi_phy_if_0_data_hs_n[0]}]

set_property DIFF_TERM TRUE [get_ports mipi_phy_if_1_clk_hs_p]
set_property DIFF_TERM TRUE [get_ports mipi_phy_if_1_clk_hs_n]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_p[3]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_n[3]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_p[2]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_n[2]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_p[1]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_n[1]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_p[0]}]
set_property DIFF_TERM TRUE [get_ports {mipi_phy_if_1_data_hs_n[0]}]

set_property -dict {PACKAGE_PIN Y6 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_n]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD TMDS_33} [get_ports TMDS_0_clk_p]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[0]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[0]}]

set_property -dict {PACKAGE_PIN V7 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[1]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[1]}]

set_property -dict {PACKAGE_PIN W8 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_n[2]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD TMDS_33} [get_ports {TMDS_0_data_p[2]}]

set_property -dict { PACKAGE_PIN T5   IOSTANDARD LVCMOS33 } [get_ports { hdmi_out_ddc_scl_io }]
set_property -dict { PACKAGE_PIN U5   IOSTANDARD LVCMOS33 } [get_ports { hdmi_out_ddc_sda_io }]

set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS25} [get_ports {CAM_RESET[0]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS25} [get_ports {CAM_ENABLE[0]}]

set_property -dict {PACKAGE_PIN U20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[0]}]
set_property -dict {PACKAGE_PIN Y18  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[1]}]
set_property -dict {PACKAGE_PIN R16  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[2]}]
set_property -dict {PACKAGE_PIN P20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[3]}]
set_property -dict {PACKAGE_PIN Y19  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[4]}]
set_property -dict {PACKAGE_PIN U19  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[5]}]
set_property -dict {PACKAGE_PIN V20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[6]}]
set_property -dict {PACKAGE_PIN U18  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[7]}]
set_property -dict {PACKAGE_PIN P19  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[8]}]
set_property -dict {PACKAGE_PIN W19  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[9]}]
set_property -dict {PACKAGE_PIN N20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[10]}]
set_property -dict {PACKAGE_PIN W20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[11]}]
set_property -dict {PACKAGE_PIN T20  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[12]}]
set_property -dict {PACKAGE_PIN R18  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[13]}]
set_property -dict {PACKAGE_PIN W15  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[14]}]
set_property -dict {PACKAGE_PIN T17  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[15]}]
set_property -dict {PACKAGE_PIN U13  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[16]}]
set_property -dict {PACKAGE_PIN U15  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[17]}]
set_property -dict {PACKAGE_PIN T14  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[18]}]
set_property -dict {PACKAGE_PIN W13  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[19]}]
set_property -dict {PACKAGE_PIN U17  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[20]}]
set_property -dict {PACKAGE_PIN T15  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[21]}]
set_property -dict {PACKAGE_PIN U12  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[22]}]
set_property -dict {PACKAGE_PIN V12  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[23]}]
set_property -dict {PACKAGE_PIN U14  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[24]}]
set_property -dict {PACKAGE_PIN Y14  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[25]}]
set_property -dict {PACKAGE_PIN T16  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[26]}]
set_property -dict {PACKAGE_PIN P14  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[27]}]
set_property -dict {PACKAGE_PIN V18  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[28]}]
set_property -dict {PACKAGE_PIN T12  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[29]}]
set_property -dict {PACKAGE_PIN V17  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[30]}]
set_property -dict {PACKAGE_PIN W16  IOSTANDARD LVCMOS18} [get_ports {GPIF_DATA[31]}]
set_property -dict {PACKAGE_PIN V15  IOSTANDARD LVCMOS18} [get_ports {GPIF_LSYNC}]
set_property -dict {PACKAGE_PIN Y17  IOSTANDARD LVCMOS18} [get_ports {GPIF_FSYNC}]
set_property -dict {PACKAGE_PIN N18  IOSTANDARD LVCMOS18} [get_ports {GPIF_CLK}]
set_property -dict {PACKAGE_PIN Y16  IOSTANDARD LVCMOS18} [get_ports {GPIF_GPIO22}]

set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS18} [get_ports xvs_0]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS18} [get_ports xhs_0]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS18} [get_ports xmaster_0]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS18} [get_ports xtrig1_0]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS18} [get_ports xtrig2_0]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS18} [get_ports native_strobe_in_0]

set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports opto_in_0]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports opto_out_0]

set c200      [get_clocks -quiet clk_out1_design_1_clk_wiz_0_0]
set c150      [get_clocks -quiet clk_out2_design_1_clk_wiz_0_0]
set dphy_bclk [get_clocks -quiet -of_objects [get_pins -quiet design_1_i/mipi_dphy_0/rxbyteclkhs]]
set_max_delay -quiet -datapath_only -from $c200 -to $c150      6.667
set_max_delay -quiet -datapath_only -from $c200 -to $dphy_bclk 6.400
